### ISSUE TITLE
アラーム機能

### ISSUE THREAD

**Issue by sachi-github** [bisnii/hacku#10]
**眠りを検知したら自動的にアラームを設定する機能**

ツール：JavaScript

- [x] 対象者の睡眠状態の取得（眠っていたら以下をの処理を行う）
- [x] 設定された時間でアラームをセットし、カウントダウンスタート
- [x] カウントダウンのタイム表示
- [x] 睡眠中に設定されたbgmを流す（追加機能）
- [x] 対象者が退席・作業状態になったらカウントダウンリセット
- [x] カウントが0になったら設定されたアラームを鳴らす（ベルなど）
- [x] タイピングゲーム（追加機能）をクリアするまでアラームを鳴らし続け、クリアしたら止める
- [x] （タイピングゲームができるまでは一定時間経つ、若しくはボタンを押すことで止める）

**Comment by yochimonji** [comment]
タスク書きだしてくれてありがたい！
質問なんだけどアラーム機能はJavaScriptで実装予定？

**Comment by sachi-github** [comment]
なんか他に必要そうなタスクあったらお願い！
現段階ではjavascriptだけの予定

**Comment by yochimonji** [comment]
他に必要そうなことは
- アラームまでのカウントダウンの表示
- 睡眠中に他の状態（作業中・退席中）に変化したらカウントダウンをリセット

があると思う。それ以外はとりあえず大丈夫！

JavaScriptだけやねー、了解！

**Comment by sachi-github** [comment]
了解！
