### ISSUE TITLE
プログラム全体の流れ

### ISSUE THREAD

**Issue by yochimonji** [bisnii/hacku#11]
プログラム全体のざっくりとした流れを書きます．とりあえず最低限だけ書いて後で書き足します．このほうが作りやすい！とかここがわからん？とかあればコメントお願いします！（本来はクラス図とか書いたほうがいいんだろうけどよくわからん...）

#### 居眠り検知
言語：Python
入力：画像
出力：活動状態（作業中・睡眠中・退席中）
画像から活動状態を予測
#### カウントダウン
言語：JavaScript
入力：活動状態、何分後に起こすかの設定値
出力：現在のカウント
アラームまでの時間表示とアラームを鳴らすのに使用
#### アラーム
言語：JavaScript
入力：アラーム音
出力：なし
呼び出されたら入力されたアラーム音を鳴らす
#### タイピングゲーム
言語：？
入力：なし
出力：なし
タイピングゲームを行う．タイピングゲーム中はアラームが鳴り続ける．

### プログラムの流れ
1. 一定時間ごとにWebカメラから画像を取得
2. 居眠り検知プログラムにPOSTで画像を送信
3. 居眠り検知プログラムからのレスポンス（活動状態）を受信
4. レスポンスが睡眠中の場合、カウントダウンプログラムを呼び出し
5. 活動状態が変化したらカウントダウンプログラムを停止
6. カウントダウンが0になった場合、カウントダウンプログラムがアラームプログラムを呼び出し
7. アラームプログラムはアラームを鳴らして、タイピングゲームを呼び出す
8. タイピングゲームが終了したら、アラームプログラムも終了する

<br>
ちなみにプログラムを実行する場合、以下のコマンドでサーバーを起動させる予定です．できるようになったら連絡します．

```
python app.py
```

**Comment by sachi-github** [comment]
ありがと！
#5 ではタイピングゲームは追加機能になっとったけど必須機能っていう解釈でよい？

**Comment by yochimonji** [comment]
#10 を見る前に書いたから混乱させてしまったかもしれん…
とりあえず#10 の通りにタイピングゲームは追加機能でお願いします。
タイピングゲームはアラーム機能ができ次第取り掛かるという感じでいいと思う

**Comment by sachi-github** [comment]
了解しました！
