### ISSUE TITLE
アプリ名の案

### ISSUE THREAD

**Issue by yochimonji** [bisnii/hacku#16]
タイトル案をお願いします。

PC作業のサポーター
白雪姫

**Comment by yochimonji** [comment]
Support
Engineer
developer
などの組み合わせ

**Comment by yochimonji** [comment]
P-Cupport

**Comment by junki3737** [comment]
- reboot
- refresh
- clear
コマンドみたいなものもいいかも

**Comment by sachi-github** [comment]
とりあえず1つの案として

案: Re:work
      Reは動詞の意味を補助する
      workは作業
      ⇒作業を補助するアプリ
      (reworkの本来の意味は再作業なので休む時は休んで作業を再開しようという意味も含められる？)←後付け

**Comment by sachi-github** [comment]
ワード

- やるときはやる、休む時は休む（メリハリ）
- 寝てもいいよ
- 作業 work job 
- helper
- supporter
- assistant

**Comment by sachi-github** [comment]
work out・・・いい結果になる
work on・・・取り組む
work it・・・うまくやる

メリハリをつける・・・change the pace

**Comment by junki3737** [comment]
Reboot Sleeper
